import { Helmet, Alert, Gateway, SystemStats } from './types';

export const mockHelmets: Helmet[] = [
  {
    id: 'HLM-001',
    workerId: 'WRK-001',
    workerName: 'John Hartley',
    status: 'active',
    co: 8,
    ch4: 0.5,
    temperature: 32,
    humidity: 65,
    helmetWear: true,
    impactDetected: false,
    battery: 92,
    signalStrength: -45,
    gatewayId: 'GW-001',
    lastUpdate: new Date(Date.now() - 5000),
  },
  {
    id: 'HLM-002',
    workerId: 'WRK-002',
    workerName: 'Sarah Mitchell',
    status: 'active',
    co: 12,
    ch4: 0.8,
    temperature: 34,
    humidity: 72,
    helmetWear: true,
    impactDetected: false,
    battery: 87,
    signalStrength: -52,
    gatewayId: 'GW-001',
    lastUpdate: new Date(Date.now() - 3000),
  },
  {
    id: 'HLM-003',
    workerId: 'WRK-003',
    workerName: 'Michael Chen',
    status: 'alarm',
    co: 45,
    ch4: 2.1,
    temperature: 38,
    humidity: 78,
    helmetWear: false,
    impactDetected: true,
    battery: 65,
    signalStrength: -68,
    gatewayId: 'GW-002',
    lastUpdate: new Date(Date.now() - 1000),
  },
  {
    id: 'HLM-004',
    workerId: 'WRK-004',
    workerName: 'Emily Rodriguez',
    status: 'active',
    co: 10,
    ch4: 0.6,
    temperature: 31,
    humidity: 68,
    helmetWear: true,
    impactDetected: false,
    battery: 94,
    signalStrength: -40,
    gatewayId: 'GW-001',
    lastUpdate: new Date(Date.now() - 4000),
  },
  {
    id: 'HLM-005',
    workerId: 'WRK-005',
    workerName: 'David Thompson',
    status: 'active',
    co: 15,
    ch4: 0.9,
    temperature: 35,
    humidity: 75,
    helmetWear: true,
    impactDetected: false,
    battery: 78,
    signalStrength: -55,
    gatewayId: 'GW-002',
    lastUpdate: new Date(Date.now() - 2000),
  },
  {
    id: 'HLM-006',
    workerId: 'WRK-006',
    workerName: 'Lisa Anderson',
    status: 'inactive',
    co: 5,
    ch4: 0.2,
    temperature: 25,
    humidity: 45,
    helmetWear: false,
    impactDetected: false,
    battery: 20,
    signalStrength: -85,
    gatewayId: 'GW-003',
    lastUpdate: new Date(Date.now() - 300000),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'ALT-001',
    helmetId: 'HLM-003',
    workerName: 'Michael Chen',
    type: 'CO Level High',
    level: 'critical',
    message: 'CO level exceeded critical threshold (45 ppm)',
    timestamp: new Date(Date.now() - 1000),
    resolved: false,
  },
  {
    id: 'ALT-002',
    helmetId: 'HLM-003',
    workerName: 'Michael Chen',
    type: 'Impact Detected',
    level: 'critical',
    message: 'Impact detected - immediate response recommended',
    timestamp: new Date(Date.now() - 2000),
    resolved: false,
  },
  {
    id: 'ALT-003',
    helmetId: 'HLM-003',
    workerName: 'Michael Chen',
    type: 'Helmet Not Worn',
    level: 'warning',
    message: 'Worker is not wearing helmet',
    timestamp: new Date(Date.now() - 3000),
    resolved: false,
  },
  {
    id: 'ALT-004',
    helmetId: 'HLM-002',
    workerName: 'Sarah Mitchell',
    type: 'CH4 Level Warning',
    level: 'warning',
    message: 'Methane level in warning range (0.8%)',
    timestamp: new Date(Date.now() - 30000),
    resolved: true,
  },
  {
    id: 'ALT-005',
    helmetId: 'HLM-005',
    workerName: 'David Thompson',
    type: 'Battery Low',
    level: 'warning',
    message: 'Battery level below 80%',
    timestamp: new Date(Date.now() - 60000),
    resolved: false,
  },
];

export const mockGateways: Gateway[] = [
  {
    id: 'GW-001',
    location: 'North Shaft',
    status: 'online',
    connectedHelmets: 3,
    signalStrength: 95,
    lastHeartbeat: new Date(Date.now() - 2000),
  },
  {
    id: 'GW-002',
    location: 'South Shaft',
    status: 'online',
    connectedHelmets: 2,
    signalStrength: 88,
    lastHeartbeat: new Date(Date.now() - 3000),
  },
  {
    id: 'GW-003',
    location: 'East Tunnel',
    status: 'offline',
    connectedHelmets: 1,
    signalStrength: 0,
    lastHeartbeat: new Date(Date.now() - 180000),
  },
];

export const mockSystemStats: SystemStats = {
  totalHelmets: 6,
  activeHelmets: 5,
  criticalAlerts: 2,
  avgGasLevel: 14.5,
  complianceRate: 83,
};

export const alertTrendData = [
  { name: '00:00', value: 0 },
  { name: '02:00', value: 1 },
  { name: '04:00', value: 2 },
  { name: '06:00', value: 3 },
  { name: '08:00', value: 5 },
  { name: '10:00', value: 4 },
  { name: '12:00', value: 3 },
  { name: '14:00', value: 5 },
  { name: '16:00', value: 7 },
  { name: '18:00', value: 6 },
  { name: '20:00', value: 4 },
  { name: '22:00', value: 3 },
  { name: '24:00', value: 2 },
];

export const gasLevelData = [
  { name: 'CO Safe', value: 45 },
  { name: 'CO Warning', value: 12 },
  { name: 'CO Critical', value: 1 },
  { name: 'CH4 Safe', value: 54 },
  { name: 'CH4 Warning', value: 3 },
  { name: 'CH4 Critical', value: 0 },
];

export const temperatureData = [
  { name: '06:00', value: 28 },
  { name: '07:00', value: 29 },
  { name: '08:00', value: 30 },
  { name: '09:00', value: 31 },
  { name: '10:00', value: 32 },
  { name: '11:00', value: 33 },
  { name: '12:00', value: 34 },
  { name: '13:00', value: 35 },
  { name: '14:00', value: 35 },
  { name: '15:00', value: 35 },
  { name: '16:00', value: 34 },
  { name: '17:00', value: 33 },
  { name: '18:00', value: 33 },
  { name: '19:00', value: 32 },
  { name: '20:00', value: 31 },
  { name: '21:00', value: 31 },
  { name: '22:00', value: 30 },
  { name: '23:00', value: 29 },
  { name: '24:00', value: 29 },
];

export const humidityData = [
  { name: '06:00', value: 55 },
  { name: '07:00', value: 58 },
  { name: '08:00', value: 60 },
  { name: '09:00', value: 62 },
  { name: '10:00', value: 64 },
  { name: '11:00', value: 66 },
  { name: '12:00', value: 68 },
  { name: '13:00', value: 70 },
  { name: '14:00', value: 72 },
  { name: '15:00', value: 75 },
  { name: '16:00', value: 74 },
  { name: '17:00', value: 72 },
  { name: '18:00', value: 72 },
  { name: '19:00', value: 70 },
  { name: '20:00', value: 68 },
  { name: '21:00', value: 68 },
  { name: '22:00', value: 65 },
  { name: '23:00', value: 62 },
  { name: '24:00', value: 60 },
];

export const impactData = [
  { name: 'Mon', value: 2 },
  { name: 'Tue', value: 1 },
  { name: 'Wed', value: 3 },
  { name: 'Thu', value: 1 },
  { name: 'Fri', value: 2 },
  { name: 'Sat', value: 0 },
  { name: 'Sun', value: 1 },
];

export const complianceData = [
  { name: 'Mon', value: 85 },
  { name: 'Tue', value: 88 },
  { name: 'Wed', value: 86 },
  { name: 'Thu', value: 90 },
  { name: 'Fri', value: 92 },
  { name: 'Sat', value: 83 },
  { name: 'Sun', value: 81 },
];

export const helmetDetailedData = [
  {
    id: 'HLM-001',
    name: 'John Hartley',
    location: 'North Shaft - Level 2',
    co: 8,
    ch4: 0.5,
    temp: 32,
    humidity: 65,
    battery: 92,
    signal: -45,
    status: 'Safe',
    lastUpdate: new Date(Date.now() - 5000),
  },
  {
    id: 'HLM-002',
    name: 'Sarah Mitchell',
    location: 'North Shaft - Level 3',
    co: 12,
    ch4: 0.8,
    temp: 34,
    humidity: 72,
    battery: 87,
    signal: -52,
    status: 'Safe',
    lastUpdate: new Date(Date.now() - 3000),
  },
  {
    id: 'HLM-003',
    name: 'Michael Chen',
    location: 'South Shaft - Level 1',
    co: 45,
    ch4: 2.1,
    temp: 38,
    humidity: 78,
    battery: 65,
    signal: -68,
    status: 'Critical',
    lastUpdate: new Date(Date.now() - 1000),
  },
  {
    id: 'HLM-004',
    name: 'Emily Rodriguez',
    location: 'North Shaft - Level 4',
    co: 10,
    ch4: 0.6,
    temp: 31,
    humidity: 68,
    battery: 94,
    signal: -40,
    status: 'Safe',
    lastUpdate: new Date(Date.now() - 4000),
  },
  {
    id: 'HLM-005',
    name: 'David Thompson',
    location: 'South Shaft - Level 2',
    co: 15,
    ch4: 0.9,
    temp: 35,
    humidity: 75,
    battery: 78,
    signal: -55,
    status: 'Safe',
    lastUpdate: new Date(Date.now() - 2000),
  },
  {
    id: 'HLM-006',
    name: 'Lisa Anderson',
    location: 'East Tunnel - Level 1',
    co: 5,
    ch4: 0.2,
    temp: 25,
    humidity: 45,
    battery: 20,
    signal: -85,
    status: 'Offline',
    lastUpdate: new Date(Date.now() - 300000),
  },
];

// Admin Portal Mock Data
export const mockSupervisors = [
  {
    id: 'SUP-001',
    name: 'Robert Williams',
    email: 'robert.williams@mining.com',
    location: 'North Shaft Operations',
    status: 'active',
    assignedWorkers: 12,
    assignedGateways: 3,
    lastActive: new Date(Date.now() - 5000),
    joinDate: new Date('2024-01-15'),
  },
  {
    id: 'SUP-002',
    name: 'Margaret Davis',
    email: 'margaret.davis@mining.com',
    location: 'South Shaft Operations',
    status: 'active',
    assignedWorkers: 8,
    assignedGateways: 2,
    lastActive: new Date(Date.now() - 60000),
    joinDate: new Date('2024-02-20'),
  },
  {
    id: 'SUP-003',
    name: 'James Patterson',
    email: 'james.patterson@mining.com',
    location: 'East Tunnel Operations',
    status: 'inactive',
    assignedWorkers: 5,
    assignedGateways: 1,
    lastActive: new Date(Date.now() - 86400000),
    joinDate: new Date('2024-03-10'),
  },
  {
    id: 'SUP-004',
    name: 'Elizabeth Johnson',
    email: 'elizabeth.johnson@mining.com',
    location: 'West Sector Operations',
    status: 'active',
    assignedWorkers: 10,
    assignedGateways: 2,
    lastActive: new Date(Date.now() - 300000),
    joinDate: new Date('2024-01-25'),
  },
];

export const mockWorkers = [
  {
    id: 'WRK-001',
    name: 'John Hartley',
    email: 'john.hartley@mining.com',
    phone: '+1-555-0101',
    department: 'Operations',
    supervisor: 'Robert Williams',
    status: 'active',
    helmets: 1,
    joinDate: new Date('2023-06-15'),
  },
  {
    id: 'WRK-002',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@mining.com',
    phone: '+1-555-0102',
    department: 'Operations',
    supervisor: 'Robert Williams',
    status: 'active',
    helmets: 1,
    joinDate: new Date('2023-07-20'),
  },
  {
    id: 'WRK-003',
    name: 'Michael Chen',
    email: 'michael.chen@mining.com',
    phone: '+1-555-0103',
    department: 'Maintenance',
    supervisor: 'Margaret Davis',
    status: 'active',
    helmets: 1,
    joinDate: new Date('2023-08-10'),
  },
  {
    id: 'WRK-004',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@mining.com',
    phone: '+1-555-0104',
    department: 'Operations',
    supervisor: 'Robert Williams',
    status: 'inactive',
    helmets: 0,
    joinDate: new Date('2023-09-05'),
  },
  {
    id: 'WRK-005',
    name: 'David Thompson',
    email: 'david.thompson@mining.com',
    phone: '+1-555-0105',
    department: 'Operations',
    supervisor: 'Margaret Davis',
    status: 'active',
    helmets: 1,
    joinDate: new Date('2023-10-12'),
  },
];

export const mockAuditLogs = [
  {
    id: 'LOG-001',
    action: 'Helmet Status Changed',
    target: 'HLM-003',
    targetName: 'Michael Chen Helmet',
    user: 'Robert Williams',
    timestamp: new Date(Date.now() - 300000),
    details: 'Status changed to CRITICAL - High CO levels',
    severity: 'critical',
  },
  {
    id: 'LOG-002',
    action: 'Worker Added',
    target: 'WRK-006',
    targetName: 'New Worker',
    user: 'Admin',
    timestamp: new Date(Date.now() - 1800000),
    details: 'New worker registered to North Shaft Operations',
    severity: 'info',
  },
  {
    id: 'LOG-003',
    action: 'Supervisor Deactivated',
    target: 'SUP-003',
    targetName: 'James Patterson',
    user: 'Admin',
    timestamp: new Date(Date.now() - 3600000),
    details: 'Supervisor account deactivated due to inactivity',
    severity: 'warning',
  },
];

export const adminSystemStats = {
  totalSupervisors: 4,
  activeSupervisors: 3,
  totalWorkers: 25,
  activeWorkers: 22,
  totalGateways: 3,
  onlineGateways: 2,
  systemHealth: 96,
  alertsToday: 15,
  criticalAlerts: 2,
};
